cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
  paths:
    - .composer/
    - .php_cs.cache

variables:
  COMPOSER_CACHE_DIR: ".composer"
  TYPO3_PATH_WEB: "$CI_PROJECT_DIR/.build/public"
  MYSQL_DATABASE: "typo3"
  MYSQL_ROOT_PASSWORD: "joh316"
  typo3DatabaseName: "typo3"
  typo3DatabaseHost: "mysql"
  typo3DatabaseUsername: "root"
  typo3DatabasePassword: "joh316"

before_script:
  - apk add git --update

stages:
  - lint
  - test
  - documentation
  - analysis

lint:cgl:
  image: php:8.1-alpine
  stage: lint
  before_script:
    - apk add --no-cache bash curl git mercurial openssh openssl parallel subversion tini zlib-dev libzip-dev zip icu-dev g++
    - docker-php-ext-install mysqli && docker-php-ext-install zip && docker-php-ext-configure intl && docker-php-ext-install intl && docker-php-ext-enable intl
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php --no-ansi --install-dir=/usr/bin --filename=composer
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - sed -i -e "s#ssh://git@code.extco.de:22722#https://gitlab-ci-token:$CI_JOB_TOKEN@code.extco.de#g" composer.json
    - composer config platform.php 8.1
    - composer remove typo3/cms-core --no-update
    - composer install --no-progress --no-ansi --no-interaction
  script:
    - vendor/bin/php-cs-fixer fix --config=Build/.php-cs-fixer.dist.php -v --dry-run --using-cache=no --path-mode=intersection ./

lint:typoscriptcgl:
  image: php:8.1-alpine
  stage: lint
  before_script:
    - apk add --no-cache bash curl git mercurial openssh openssl parallel subversion tini zlib-dev libzip-dev zip icu-dev g++
    - docker-php-ext-install mysqli && docker-php-ext-install zip && docker-php-ext-configure intl && docker-php-ext-install intl && docker-php-ext-enable intl
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php --no-ansi --install-dir=/usr/bin --filename=composer
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - sed -i -e "s#ssh://git@code.extco.de:22722#https://gitlab-ci-token:$CI_JOB_TOKEN@code.extco.de#g" composer.json
    - composer config platform.php 8.1
    - composer remove typo3/cms-core --no-update
    - composer install --no-progress --no-ansi --no-interaction
  script:
    - vendor/bin/typoscript-lint -c Build/typoscriptlint.yaml Configuration

lint:yaml:
  stage: lint
  image: python:alpine3.7
  before_script:
    - pip install yamllint==1.10.0
  script:
    - yamllint -c Build/yamllint.yaml Configuration/ Resources/

lint:php81:
  stage: lint
  image: php:8.1-alpine
  script:
    - find . -name \*.php -exec php -l "{}" \;

lint:php82:
  stage: lint
  image: php:8.2-alpine
  script:
    - find . -name \*.php -exec php -l "{}" \;

lint:php83:
  stage: lint
  image: php:8.3-alpine
  script:
    - find . -name \*.php -exec php -l "{}" \;

phpstan:analyse:
  image: php:8.1-alpine
  stage: lint
  before_script:
    - apk add --no-cache bash curl git mercurial openssh openssl parallel subversion tini zlib-dev libzip-dev zip icu-dev g++
    - docker-php-ext-install mysqli && docker-php-ext-install zip && docker-php-ext-configure intl && docker-php-ext-install intl && docker-php-ext-enable intl
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php --no-ansi --install-dir=/usr/bin --filename=composer
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - sed -i -e "s#ssh://git@code.extco.de:22722#https://gitlab-ci-token:$CI_JOB_TOKEN@code.extco.de#g" composer.json
    - composer install --no-progress --no-ansi --no-interaction
  script:
    - vendor/bin/phpstan analyse -c Build/phpstan.neon --memory-limit 256M

.test_php: &test_php
  stage: test
  services:
  - mysql:5
  image: php:$DOCKER_TAG
  only:
    - branches
  before_script:
    - apk add --no-cache bash curl git mercurial openssh openssl parallel subversion tini zlib-dev libzip-dev zip icu-dev g++
    - >
      if [[ "$COVERAGE" == "1" ]]; then
        apk add --no-cache linux-headers $PHPIZE_DEPS
        pecl install xdebug && docker-php-ext-enable xdebug
      fi
    - docker-php-ext-install mysqli && docker-php-ext-install zip && docker-php-ext-configure intl && docker-php-ext-install intl && docker-php-ext-enable intl
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php --no-ansi --install-dir=/usr/bin --filename=composer
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - sed -i -e "s#ssh://git@code.extco.de:22722#https://gitlab-ci-token:$CI_JOB_TOKEN@code.extco.de#g" composer.json
    - composer config --no-plugins allow-plugins.typo3/cms-composer-installers true
    - composer config --no-plugins allow-plugins.typo3/class-alias-loader true
    - composer require typo3/cms-core="${TYPO3_VERSION}"
  script:
    - >
      if [[ "$COVERAGE" == "0" ]]; then
        vendor/bin/phpunit -c Build/UnitTests.xml
      fi
    - >
      if [[ "$COVERAGE" == "1" ]]; then
        XDEBUG_MODE=coverage TYPO3_PATH_WEB=${TYPO3_PATH_WEB} vendor/bin/phpunit --coverage-clover=phpunit.coverage.xml --log-junit=phpunit.report.xml -c Build/UnitTests.xml Tests/Unit
      fi
#    - typo3DatabaseDriver=pdo_sqlite vendor/bin/phpunit -c Build/FunctionalTests.xml
  artifacts:
    paths:
      - phpunit.coverage.xml
      - phpunit.report.xml
    expire_in: 1 day
    when: always

# Build in PHP 8.1 and TYPO3 12.4
test:php81:typo3_12:
  <<: *test_php
  variables:
    DOCKER_TAG: 8.1-alpine
    TYPO3_VERSION: ^12.4
    COVERAGE: 0

# Build in PHP 8.2 and TYPO3 12.4
test:php82:typo3_12:
  <<: *test_php
  variables:
    DOCKER_TAG: 8.2-alpine
    TYPO3_VERSION: ^12.4
    COVERAGE: 0

# Build in PHP 8.3 and TYPO3 12.4
test:php83:typo3_12:
  <<: *test_php
  variables:
    DOCKER_TAG: 8.3-alpine
    TYPO3_VERSION: ^12.4
    COVERAGE: 1

.test_codeception: &test_codeception
  stage: test
  services:
    - mysql:5
  image: php:$DOCKER_TAG
  only:
    - branches
  before_script:
    - apk add --no-cache bash curl git mercurial openssh openssl parallel subversion tini zlib-dev libzip-dev zip icu-dev g++ firefox
    - docker-php-ext-install mysqli && docker-php-ext-install zip && docker-php-ext-configure intl && docker-php-ext-install intl && docker-php-ext-enable intl
    - wget https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
    - tar -xvzf geckodriver*
    - chmod +x geckodriver
    - mv geckodriver /usr/local/bin/
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php --no-ansi --install-dir=/usr/bin --filename=composer
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - sed -i -e "s#ssh://git@code.extco.de:22722#https://gitlab-ci-token:$CI_JOB_TOKEN@code.extco.de#g" composer.json
    - composer config --no-plugins allow-plugins.typo3/cms-composer-installers true
    - composer config --no-plugins allow-plugins.typo3/class-alias-loader true
    - composer require typo3/cms-core="${TYPO3_VERSION}"
  script:
    - geckodriver &
    - mkdir -p .build/public/typo3temp/var/tests/acceptance-sqlite-dbs
    - export INSTANCE_PATH="$(pwd)/.build/public/typo3temp/var/tests/acceptance"
    - vendor/bin/codecept build
    - vendor/bin/codecept run
  artifacts:
    paths:
      - .build/Tests/Acceptance/_output
      - .build/public/typo3temp/var/tests/acceptance/typo3temp/var/log
    expire_in: 1 day
    when: always

# Build in PHP 8.1 and TYPO3 12.4
test:codception:php81:typo3_12:
  <<: *test_codeception
  variables:
    DOCKER_TAG: 8.1-alpine
    TYPO3_VERSION: ^12.4
    GECKODRIVER_VERSION: v0.34.0

# Build in PHP 8.2 and TYPO3 12.4
test:codception:php82:typo3_12:
  <<: *test_codeception
  needs:
    - test:codception:php81:typo3_12
  variables:
    DOCKER_TAG: 8.2-alpine
    TYPO3_VERSION: ^12.4
    GECKODRIVER_VERSION: v0.34.0

# Build in PHP 8.3 and TYPO3 12.4
test:codception:php83:typo3_12:
  <<: *test_codeception
  needs:
    - test:codception:php82:typo3_12
  variables:
    DOCKER_TAG: 8.3-alpine
    TYPO3_VERSION: ^12.4
    GECKODRIVER_VERSION: v0.34.0

documentation:
  stage: documentation
  image:
    name: t3docs/render-documentation:v2.4.0
    entrypoint: [""]
  before_script:
    - cp -a ${CI_PROJECT_DIR}/. /PROJECT
    - mkdir -p ${CI_PROJECT_DIR}/Documentation-GENERATED-temp
  script:
    - cd /ALL/venv
    - /ALL/Menu/mainmenu.sh makehtml-no-cache -c resultdir ${CI_PROJECT_DIR}/Documentation-GENERATED-temp
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/Documentation-GENERATED-temp/Result/project/0.0.0
    expire_in: 1 day
    when: always

sonarqube:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: "https://sonar.extco.de"
    SONAR_PROJECT_NAME: "$CI_PROJECT_NAME"
    SONAR_TOKEN: "$SONAR_TOKEN"
    SONAR_PROJECT_VERSION: "$CI_JOB_ID"
    SONAR_ANALYSIS_MODE: "issues"
    SONAR_SOURCES: "./Classes"
    SONAR_GITLAB_PROJECT_ID: "$CI_PROJECT_ID"
  script:
    - echo "sonar.projectKey=cart_products-5.x" > sonar-project.properties
    - gitlab-sonar-scanner -Dsonar.php.coverage.reportPath=phpunit.coverage.xml -Dsonar.php.tests.reportPath=phpunit.report.xml
  allow_failure: true

sonarqube-reports:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: "https://sonar.extco.de"
    SONAR_PROJECT_NAME: "$CI_PROJECT_NAME"
    SONAR_TOKEN: "$SONAR_TOKEN"
    SONAR_PROJECT_VERSION: "$CI_JOB_ID"
    SONAR_ANALYSIS_MODE: "publish"
    SONAR_SOURCES: "./Classes"
    SONAR_TESTS: "./Tests"
  script:
    - echo "sonar.projectKey=cart_products-5.x" > sonar-project.properties
    - gitlab-sonar-scanner -Dsonar.php.coverage.reportPath=phpunit.coverage.xml -Dsonar.php.tests.reportPath=phpunit.report.xml
